version: '2'
services:
  web:
    build: ./web
    restart: always    
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: ./app
    restart: always    
#    ports:
#      - 5000:5000
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always    
#    ports:
#      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
